name: Publish Launcher

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Elevate launcher script permissions
        run: chmod +x ./launch.sh

      - name: Zip Launcher files
        run: zip -j ZenithProxyLauncher.zip launch.sh launch.bat launcher.py update_launcher.py setup.py cacert.pem

      - name: Publish Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: "launcher"
          artifacts: "launcher.py,ZenithProxyLauncher.zip"
          allowUpdates: true
          replacesArtifacts: true
          omitBodyDuringUpdate: true
          makeLatest: true
