name: 1.20.1 Build and Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+\+1.20.1.pre'
      - '[0-9]+.[0-9]+.[0-9]+\+1.20.1'

jobs:
  build-java-and-linux-amd64:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
